### ISSUE TITLE
project1写得很好，赞

### ISSUE THREAD

**Issue by Yitong806** [YanWQ-monad/SUSTech_CS205_Projects#1]
在bb系统看了你的report，写得很不错。我也读了你写的对于22春季的Java1A的第四次作业的建议，有机会听到其他SA的声音。
那题的构想是我从头到尾一个人设计的，并没有某门课程的project涉及到高精度的计算，也不存在超前知识的问题。

以我对BigBinary题答疑的经验来看，有争议的主要原因是大部分同学没好好读题，没看清题目就直接写；以及有一些同学写代码沉不下心，心浮气躁地写出了很多bugs。这个题目很符合我的出题风格：要好好锻炼同学们的**阅读能力**和**代码书写能力**；对于不好好读题或者不好好写代码的同学，**一分都不应该给**。

**Comment by YanWQ-monad** [comment]
不好意思，上学期关于 Assignment 4 的轶事是我道听途说来的，很抱歉没有经过核实就写出来了。那个评价也不只是针对那次 Assignment，当时**听说**也有其它 Assignment 也是（~~只是我忘了~~）。不过无论如何，这些都是一些流言传闻，如果我帮他们再说一遍，就相当于我也有责任。为了避免产生不好的影响，相关部份已经删掉了，非常感谢你的建议。

从我个人角度来看，Assignment 4 还是非常好的，至少我写起来还挺舒服的，还能让我有兴趣写下两种不同的实现。

然后非常感谢可以听到你对本 Project 的肯定。 ~~也希望这个 Project 不会让同学们都卷起来。~~

**Comment by Yitong806** [comment]
加油，希望大佬这学期cpp能做出更加精彩的project。
